// Regenerates brain/people/index.md and brain/people/graph.md from entity
// frontmatter. Deterministic, zero-LLM. Run after any entity write.
//
//   node server/brain-graph.js            regenerate both files
//   node server/brain-graph.js --check    exit 1 if files are stale or entities are broken

import fs from "node:fs";
import path from "node:path";
import { BRAIN_ROOT, listEntities, edgesOf } from "./brain-lib.js";

const INDEX_PATH = path.join(BRAIN_ROOT, "people", "index.md");
const GRAPH_PATH = path.join(BRAIN_ROOT, "people", "graph.md");

function buildIndex(entities) {
  const people = entities.filter((e) => e.kind === "person");
  const lines = [
    "# People",
    "",
    "GENERATED by server/brain-graph.js from person frontmatter. Do not hand-edit.",
    "",
    "Yan-only directory. Read this to find a slug, then pull the entity card",
    "(node server/brain-entity-card.js <slug>) or open only that person's file.",
    "Do not glob this folder.",
    "",
  ];
  for (const p of people) {
    const slug = p.id.replace(/^people\//, "");
    const relationship = p.fields.relationship || "?";
    const aliases = Array.isArray(p.fields.aliases) ? p.fields.aliases.filter(Boolean) : [];
    let line = `- \`${slug}\` — ${p.name} (${relationship})`;
    if (aliases.length) line += ` — aliases: ${aliases.join(", ")}`;
    line += ` — \`people/${slug}/person.md\``;
    lines.push(line);
  }
  lines.push("");
  return lines.join("\n");
}

function buildGraph(entities) {
  const byId = new Map(entities.map((e) => [e.id, e]));
  const incoming = new Map();
  const dangling = [];

  for (const e of entities) {
    for (const edge of edgesOf(e)) {
      if (!byId.has(edge.to)) dangling.push(`${e.id} -> ${edge.to} (${edge.type})`);
      if (!incoming.has(edge.to)) incoming.set(edge.to, []);
      incoming.get(edge.to).push({ type: edge.type, from: e.id });
    }
  }

  const lines = [
    "# Graph",
    "",
    "GENERATED by server/brain-graph.js from entity frontmatter. Do not hand-edit.",
    "Covers all entity kinds. Only entities with at least one edge are listed;",
    "incoming edges are computed, so every relationship shows on both nodes.",
    "",
  ];

  let listed = 0;
  for (const e of entities) {
    const out = edgesOf(e);
    const inc = incoming.get(e.id) || [];
    if (!out.length && !inc.length) continue;
    listed += 1;
    lines.push(`## ${e.id} (${e.name})`);
    for (const edge of out) {
      const target = byId.get(edge.to);
      lines.push(`- ${edge.type} -> ${edge.to}${target ? ` (${target.name})` : " (MISSING)"}`);
    }
    for (const edge of inc) {
      const source = byId.get(edge.from);
      lines.push(`- ${edge.type} <- ${edge.from}${source ? ` (${source.name})` : ""}`);
    }
    lines.push("");
  }

  lines.splice(5, 0, `Entities: ${entities.length}. With edges: ${listed}. Dangling edges: ${dangling.length}.`, "");
  if (dangling.length) {
    lines.push("## Dangling edges (fix these)");
    for (const d of dangling) lines.push(`- ${d}`);
    lines.push("");
  }
  return { text: lines.join("\n"), dangling };
}

function main() {
  const check = process.argv.includes("--check");
  const { entities, problems } = listEntities();
  const index = buildIndex(entities);
  const { text: graph, dangling } = buildGraph(entities);

  if (check) {
    const staleIndex = !fs.existsSync(INDEX_PATH) || fs.readFileSync(INDEX_PATH, "utf8") !== index;
    const staleGraph = !fs.existsSync(GRAPH_PATH) || fs.readFileSync(GRAPH_PATH, "utf8") !== graph;
    for (const p of problems) console.error(`problem: ${p}`);
    for (const d of dangling) console.error(`dangling: ${d}`);
    if (staleIndex) console.error("stale: people/index.md");
    if (staleGraph) console.error("stale: people/graph.md");
    process.exit(problems.length || staleIndex || staleGraph ? 1 : 0);
  }

  fs.writeFileSync(INDEX_PATH, index);
  fs.writeFileSync(GRAPH_PATH, graph);
  console.log(`wrote people/index.md (${entities.filter((e) => e.kind === "person").length} people)`);
  console.log(`wrote people/graph.md (${entities.length} entities, ${dangling.length} dangling edges)`);
  for (const p of problems) console.error(`problem: ${p}`);
  if (problems.length) process.exit(1);
}

main();
